language: go

env:
  - GO111MODULE=on

dist: bionic

os:
  - linux
  - osx
  - windows

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
#  - master

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

go_import_path: github.com/panjf2000/gnet

script:
  - go test -v -coverprofile=coverage.txt -covermode=count -timeout 30s

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -s https://codecov.io/bash > .codecov && chmod +x .codecov && ./.codecov; else bash <(curl -s https://codecov.io/bash); fi
